"""Enterprise extension interfaces and local-compatible defaults."""

from datus.api.enterprise.defaults import (
    InMemoryEnterpriseDatasourceGrantStore,
    InMemoryEnterpriseRoleStore,
    InMemoryEnterpriseUserStore,
    InMemorySessionOwnerStore,
    LocalAuthorizationProvider,
    NoopAuditSink,
    PassthroughConfigProjector,
    SqliteEnterpriseDatasourceGrantStore,
    SqliteEnterpriseRoleStore,
    SqliteEnterpriseUserStore,
    SqliteSessionOwnerStore,
)
from datus.api.enterprise.deps import (
    SessionAccess,
    authorize,
    authorize_session_access,
    delete_session_owner,
    require_module,
)
from datus.api.enterprise.loader import EnterpriseExtensions, load_enterprise_extensions
from datus.api.enterprise.models import (
    AccessDecision,
    AuditEvent,
    ProjectionInput,
    ProjectionResult,
    ResourceRef,
)
from datus.api.enterprise.protocols import (
    ArtifactAclStore,
    AuditLogReader,
    AuditSink,
    AuthorizationProvider,
    ConfigProjector,
    EnterpriseDatasourceGrantStore,
    EnterpriseRoleStore,
    EnterpriseUserStore,
    SessionOwnerStore,
)

__all__ = [
    "AccessDecision",
    "ArtifactAclStore",
    "AuditEvent",
    "AuditLogReader",
    "AuditSink",
    "AuthorizationProvider",
    "ConfigProjector",
    "EnterpriseDatasourceGrantStore",
    "EnterpriseExtensions",
    "EnterpriseRoleStore",
    "EnterpriseUserStore",
    "InMemoryEnterpriseDatasourceGrantStore",
    "InMemoryEnterpriseRoleStore",
    "InMemoryEnterpriseUserStore",
    "InMemorySessionOwnerStore",
    "LocalAuthorizationProvider",
    "NoopAuditSink",
    "PassthroughConfigProjector",
    "ProjectionInput",
    "ProjectionResult",
    "ResourceRef",
    "SessionOwnerStore",
    "SessionAccess",
    "SqliteEnterpriseDatasourceGrantStore",
    "SqliteEnterpriseRoleStore",
    "SqliteEnterpriseUserStore",
    "SqliteSessionOwnerStore",
    "authorize",
    "authorize_session_access",
    "delete_session_owner",
    "load_enterprise_extensions",
    "require_module",
]
